spring:
  application:
    name: vocaquiz
  profiles:
    default: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID:}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:}

app:
  admin-emails: ${ADMIN_EMAILS:}

youtube:
  api-key: ${YOUTUBE_API_KEY:}
  base-url: https://www.googleapis.com/youtube/v3
